name: NPM build upon a push

on:
  release:
    types: [published]
  pull_request:
    types: [opened]
  workflow_dispatch:
    inputs:
      message:
        description: 'Message for manually triggering'
        required: false
        default: 'Triggered for Updates'
        type: string
  push:
    branches:
      - MOSIP*
      - 1.*
      - '!release-branch'
      - develop
      - master

jobs:
  build-dockers:
    strategy:
      matrix:
        include:
          - SERVICE_LOCATION: 'oidc-ui'
            SERVICE_NAME: 'oidc-ui'
          - SERVICE_LOCATION: 'oidc-server'
            SERVICE_NAME: 'oidc-server'
      fail-fast: false
    name: ${{ matrix.SERVICE_NAME }}
    uses: mosip/kattu/.github/workflows/docker-build.yml@master
    with:
      SERVICE_LOCATION: ${{ matrix.SERVICE_LOCATION }}
      SERVICE_NAME: ${{ matrix.SERVICE_NAME }}
    secrets:
      DEV_NAMESPACE_DOCKER_HUB: ${{ secrets.DEV_NAMESPACE_DOCKER_HUB }}
      ACTOR_DOCKER_HUB: ${{ secrets.ACTOR_DOCKER_HUB }}
      RELEASE_DOCKER_HUB: ${{ secrets.RELEASE_DOCKER_HUB }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}

  sonar-analysis:
    if: "${{ github.event_name != 'pull_request' }}"
    uses: mosip/kattu/.github/workflows/npm-sonar-analysis.yml@master
    with:
      SERVICE_LOCATION: ./oidc-ui
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      ORG_KEY: ${{ secrets.ORG_KEY }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
